config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("hac_shop.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path("supper/", include("hac_shop.drill_suppers.urls", namespace="drill_suppers")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

hac_shop/drill_suppers/urls.py
from django.urls import path

from . import views

app_name = "drill_suppers"
urlpatterns = [
    # ex: /polls/
    path("", views.TransactionRecordCreate.as_view(), name="index"),
    path("<pk>/", views.TransactionRecordDetail.as_view(), name="detail"),
    path(
        "<pk>/purchased", views.TransactionRecordPurchased.as_view(), name="purchased"
    ),
    path("<pk>/cancel", views.TransactionRecordCancelled.as_view(), name="cancel"),
    path("<pk>/refund", views.TransactionRecordRefund.as_view(), name="refund"),
    path("report/<pk>", views.DrillNightReport.as_view(), name="drill_night_report"),
]

hac_shop/drill_suppers/models.py
import uuid
import pytz
from datetime import datetime, timedelta, timezone, tzinfo

import stripe
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.db.models import fields
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.conf import settings

SERVER_URL = settings.STRIPE_CALLBACK_URL

HAC_TIMEZONE = settings.HAC_TIMEZONE

class AfterDrillNightCutOffError(Exception):
    pass


class DrillNightManager(models.Manager):
    def get_queryset(self):
        # Only allow dill nights that are on sale, the cut_off time is in the future
        # and the drill night is within the next 4 weeks
        return (
            super()
            .get_queryset()
            .annotate(meals_sold=models.Sum('transactionrecord__quantity', filter=models.Q(transactionrecord__status='paid')))
        )

class OnSaleManager(models.Manager):
    def get_queryset(self):
        # Only allow dill nights that are on sale, the cut_off time is in the future
        # and the drill night is within the next 4 weeks
        return (
            super()
            .get_queryset()
            .filter(
                cut_off_time__gt=datetime.now(timezone.utc),
                date_time__lt=datetime.now(timezone.utc) + timedelta(weeks=4),
                on_sale=True,
            )
        )


class DrillNight(models.Model):

    objects = DrillNightManager()
    sellable = OnSaleManager()

    date_time = models.DateTimeField()
    cut_off_time = models.DateTimeField()

    price = models.DecimalField(max_digits=5, decimal_places=2, default=5)
    annotation = models.CharField(null=True, blank=True, max_length=50, help_text="To describe special events like Gun Salutes")

    on_sale = models.BooleanField(default=True)

    class Meta:
        ordering = ['date_time']

    def __str__(self) -> str:

        if self.annotation:
            return f"{self.datetime_string} - {self.annotation}"
        else:
            return self.datetime_string

    def is_before_cut_off_time(self) -> bool:
        return datetime.now(HAC_TIMEZONE) < self.cut_off_time.replace(tzinfo=HAC_TIMEZONE)

    @property
    def date(self):
        return self.date_time.strftime("%d %b %Y")

    @property
    def day_of_week(self):
        return self.date_time.strftime("%a")

    @property
    def time(self):
        return self.date_time.strftime("%H:%M")

    @property
    def datetime_string(self):
        return self.date_time.strftime("%a %d %b %Y (%H:%M)")

    @property
    def cut_off_delta(self):
        return f"{str(self.date_time - self.cut_off_time)} before"

    def get_absolute_url(self):
        return reverse("drill_suppers:drill_night_report", args=[self.id])


class TransactionRecord(models.Model):
    class PaymentStatus(models.TextChoices):
        AWAITING_CHECKOUT = (
            "awaiting_checkout",
            "Awaiting Checkout",
        )  # The user has started the checkout process
        PAID = "paid", "Paid"  # The user completed the checkout process
        REFUNDED = (
            "refunded",
            "Refunded",
        )  # The transaction has been refunded after the payment being placed
        CANCELLED = (
            "cancelled",
            "Cancelled",
        )  # The user actively cancelled during the checkout process

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    status = models.CharField(
        choices=PaymentStatus.choices,
        max_length=31,
        default=PaymentStatus.AWAITING_CHECKOUT,
    )

    drill_night = models.ForeignKey(DrillNight, on_delete=models.CASCADE)

    name = models.CharField(max_length=512)
    email = models.EmailField()

    quantity = models.PositiveSmallIntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(5)], default=1
    )
    dietary_notes = models.TextField(blank=True, null=True)

    def __str__(self) -> str:
        return f"{self.name} - {self.drill_night}"

    def get_absolute_url(self):
        return reverse("drill_suppers:detail", args=[self.id])

    def refund(self, ignore_checks=False):

        if not self.drill_night.is_before_cut_off_time() and not ignore_checks:
            raise AfterDrillNightCutOffError

        session = self.stripecheckoutsession.get_session()

        stripe.Refund.create(payment_intent=session.payment_intent)

        self.status = TransactionRecord.PaymentStatus.REFUNDED
        self.save()


class StripeCheckoutSession(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    transaction_record = models.OneToOneField(
        TransactionRecord, on_delete=models.CASCADE
    )

    session_id = models.CharField(max_length=256, null=True, blank=True)
    checkout_url = models.TextField(null=True, blank=True)

    def get_session(self):
        return stripe.checkout.Session.retrieve(self.session_id)

    def generate_session(self) -> None:

        if self.session_id and self.checkout_url:
            return

        title = self.transaction_record.drill_night.annotation if self.transaction_record.drill_night.annotation else "Drill Night"

        checkout_session = stripe.checkout.Session.create(
            success_url=f"{SERVER_URL}/supper/{self.transaction_record.id}/purchased?session_id={{CHECKOUT_SESSION_ID}}",
            cancel_url=f"{SERVER_URL}/supper/{self.transaction_record.id}/cancel?session_id={{CHECKOUT_SESSION_ID}}",
            mode="payment",
            client_reference_id=self.transaction_record.id,
            customer_email=self.transaction_record.email,
            line_items=[
                {
                    "price_data": {
                        "currency": "GBP",
                        "product_data": {
                            "name": f"{title} on {self.transaction_record.drill_night.datetime_string}",
                        },
                        "tax_behavior": "inclusive",
                        "unit_amount": int(self.transaction_record.drill_night.price * 100),
                    },
                    "quantity": self.transaction_record.quantity,
                },
            ],
        )

        self.session_id = checkout_session.id
        self.checkout_url = checkout_session.url

        self.save()

    def verify_if_paid(self) -> bool:
        return self.get_session().payment_status == "paid"

hac_shop/drill_suppers/forms.py
from datetime import datetime, timedelta, timezone

from crispy_forms.bootstrap import FormActions
from crispy_forms.helper import FormHelper
from crispy_forms.layout import ButtonHolder, Div, Field, Fieldset, Layout, Submit
from django.core.exceptions import ValidationError
from django.forms import EmailField, Form, ModelForm

from .models import DrillNight, StripeCheckoutSession, TransactionRecord


class PurchaseForm(ModelForm):
    class Meta:
        model = TransactionRecord
        fields = ["name", "email", "drill_night", "quantity", "dietary_notes"]

        labels = {
            "name": "Your name",
            "email": "Your email",
            "quantity": "How many meals?",
            "dietary_notes": "Any dietary requirements",
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # Only show sellable drill nights
        self.fields["drill_night"].queryset = DrillNight.sellable.all()

        self.helper = FormHelper()
        self.helper.form_method = "POST"
        self.helper.layout = Layout(
            Div(
                Div(
                    Div(
                        Div(
                            Field("name"),
                            Field("email"),
                            css_class="card-body p-4",
                        ),
                        css_class="card",
                    ),
                    css_class="col",
                ),
                css_class="row mb-3",
            ),
            Div(
                Div(
                    Div(
                        Div(
                            Field("drill_night"),
                            Field("quantity"),
                            Field("dietary_notes"),
                            css_class="card-body p-4",
                        ),
                        css_class="card",
                    ),
                    css_class="col",
                ),
                css_class="row mb-3",
            ),
            Div(
                Submit("submit", "Buy", css_class="col"),
                css_class="row p-3 mb-5",
            ),
        )

    def save(self, commit: bool = True):
        obj = super().save(commit=commit)

        if commit:
            StripeCheckoutSession.objects.create(transaction_record=obj)

        return obj


class RefundForm(ModelForm):

    confirm_email = EmailField(label="Enter the email you used to book the meal")

    class Meta:
        model = TransactionRecord
        fields = ["confirm_email"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.form_method = "POST"
        self.helper.layout = Layout(
            Field("confirm_email"),
            Submit("submit", "Cancel and Refund", css_class="btn-danger"),
        )

    def clean_confirm_email(self):
        data = self.cleaned_data["confirm_email"]
        if data != self.instance.email:
            raise ValidationError("This email is not the one used to book the meal")

        # Always return a value to use as the new cleaned data, even if
        # this method didn't change it.
        return data

hac_shop/drill_suppers/views.py
from django.http.response import HttpResponse, JsonResponse
from django.shortcuts import redirect
from django.urls import reverse
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView
from django.contrib.admin.views.decorators import staff_member_required
from django.utils.decorators import method_decorator

from .forms import PurchaseForm, RefundForm
from .models import DrillNight, StripeCheckoutSession, TransactionRecord


class TransactionRecordCreate(CreateView):
    model = TransactionRecord
    form_class = PurchaseForm

    def get_success_url(self) -> str:
        checkout_session = self.object.stripecheckoutsession
        checkout_session.generate_session()
        return checkout_session.checkout_url


class TransactionRecordDetail(DetailView):
    model = TransactionRecord


class TransactionRecordPurchased(DetailView):
    model = TransactionRecord

    def get(self, request, *args: str, **kwargs):
        checkout_session_id = request.GET.get("session_id")

        if not checkout_session_id:
            return JsonResponse({"reason": "no session id"}, status=400)

        transaction_record = self.get_object()
        checkout_session = transaction_record.stripecheckoutsession

        if checkout_session.session_id != checkout_session_id:
            return JsonResponse({"reason": "incorrect session id"}, status=400)

        if checkout_session.verify_if_paid():
            transaction_record.status = TransactionRecord.PaymentStatus.PAID
            transaction_record.save()
            return redirect(transaction_record)
        else:
            return JsonResponse({"reason": "not paid"}, status=400)


class TransactionRecordCancelled(DetailView):
    model = TransactionRecord

    def get(self, request, *args: str, **kwargs):
        checkout_session_id = request.GET.get("session_id")

        if not checkout_session_id:
            return JsonResponse({"reason": "no session id"}, status=400)

        transaction_record = self.get_object()
        checkout_session = transaction_record.stripecheckoutsession

        if checkout_session.session_id != checkout_session_id:
            return JsonResponse({"reason": "incorrect session id"}, status=400)

        if checkout_session.verify_if_paid():
            transaction_record.status = TransactionRecord.PaymentStatus.CANCELLED
            transaction_record.save()
            return redirect(reverse("drill_suppers:index"))
        else:
            return JsonResponse({"reason": "not paid"}, status=400)


class TransactionRecordRefund(UpdateView):
    model = TransactionRecord
    form_class = RefundForm
    template_name = "drill_suppers/transactionrecord_refund.html"

    def form_valid(self, form):
        self.object.refund()
        return redirect(self.object)


@method_decorator(staff_member_required, name='dispatch')
class DrillNightReport(DetailView):
    model = DrillNight

hac_shop/drill_suppers/templates/drill_suppers/drillnight_detail.html
{% extends "base.html" %}
{% load tz %}


{% block title %}
  Drill Supper Booking Report
{% endblock %}

{% block content %}
  {% timezone "Europe/London" %}
  <div class="container-fluid">
    <div class="row">
      <div class="col">
        <h1>Drill Supper Booking Report</h1>
      </div>
    </div>
    <div class="row mt-5 mb-3">
      <div class="col col-md-6">
        <table class="table">
          <tbody>
            <tr>
              <th>Drill Supper:</th>
              <td>{{object}}</td>
            </tr>
            <tr>
              <th>Report Generated at:</th>
              <td>{% now "jS F Y H:i" %}</td>
            </tr>
            <tr>
              <th>Meals Sold:</th>
              <td>{{object.meals_sold}}</td>
            </tr>
          <tbody>
        </table>
      </div>
    </div>
    <div class="row">
      <div class="col">
        <table class="table table-striped">
          <thead>
            <th scope="col">Name</th>
            <th scope="col">Email</th>
            <th scope="col">Quantity</th>
            <th scope="col">Status</th>
            <th scope="col">Dietary Notes</th>
          </thead>
          <tbody>
            {% for transaction in object.transactionrecord_set.all|dictsort:"name" %}
              <tr>
                <th scope="row">
                  {% if transaction.status != "paid" %}<del>{% endif %}
                    {{transaction.name}}</th>
                  {% if transaction.status != "paid" %}</del>{% endif %}
                </th>

                <td>
                  {% if transaction.status != "paid" %}<del>{% endif %}
                    {{transaction.email}}</th>
                  {% if transaction.status != "paid" %}</del>{% endif %}
                </td>

                <td>
                  {% if transaction.status != "paid" %}<del>{% endif %}
                    {{transaction.quantity}}</th>
                  {% if transaction.status != "paid" %}</del>{% endif %}
                </td>

                <td>
                  {% if transaction.status != "paid" %}<del>{% endif %}
                    {{transaction.status}}</th>
                  {% if transaction.status != "paid" %}</del>{% endif %}
                </td>

                <td>
                  {% if transaction.status != "paid" %}<del>{% endif %}
                    {{transaction.dietary_notes}}</th>
                  {% if transaction.status != "paid" %}</del>{% endif %}
                </td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
  {% endtimezone %}
{% endblock content %}

hac_shop/drill_suppers/templates/drill_suppers/transactionrecord_detail.html
{% extends "base.html" %}
{% load tz %}


{% block title %}
  Drill Supper Booking Confirmation
{% endblock %}

{% block content %}
  {% timezone "Europe/London" %}
  <div class="container-fluid" style="max-width: 500px;">
    <div class="row mt-5">
      <div class="col">
        <div class="card">
          <div class="card-header text-muted text-center">
            {{object.pk}}
          </div>
          <div class="card-body text-center">

            {% if object.status == 'awaiting_checkout' %}
              <div class="alert alert-danger" role="alert">
                <h1>Payment not complete</h1>
                <a href="{{object.stripecheckoutsession.url}}">
                  <button class="btn btn-primary">
                    Complete your purchase
                  </button>
                </a>
              </div>
            {% elif object.status == "refunded" %}
              <div class="alert alert-warning" role="alert">
                <h1>Cancelled and Refunded</h1>
                <p>
                  Your purchase has been refunded, the money will be returned to your account within 5-10 days.
                </p>
              </div>
            {% elif object.status == "cancelled" %}
              <div class="alert alert-warning" role="alert">
                <h1>Cancelled</h1>
                <p>
                  Your purchase was cancelled before any money was taken.
                </p>
              </div>
            {% elif object.status == "paid" %}
              <div class="alert alert-success" role="alert">
                <h1>Purchase Complete</h1>
              </div>
            {% endif %}
            <p></p>
            <hr />
            <p>
              <span class="fw-bold">{{object.quantity}}x</span> Drill Suppers at the HAC<br />
              from {{object.drill_night.date_time|time:"H:i"}} on {{object.drill_night.date_time|date:"l j F"}}<br />
              for <span class="fw-bold">{{object.name}}</span>
            </p>
            {% if object.dietary_notes %}
              <h3 class="fs-6 fw-bold">Dietary Notes</h3>
              <p>{{object.dietary_notes}}
            {% endif %}
            {% if object.status == "paid" %}
              <hr />
              <h2 class="fs-5">Instructions</h3>
              <p>
                Your name and email will be on a list held by the staff on the night.
                There is no need to bring any proof of your booking. Meals will be
                available from the Sutling Room.
              </p>
              <p>
                If you change your mind, you can cancel this booking until {{object.drill_night.cut_off_time|time:"H:i"}} on {{object.drill_night.cut_off_time|date:"l j F"}}.
              </p>
            {% endif %}
          </div>
          <div class="card-footer text-muted text-center">
            {% if object.drill_night.is_before_cut_off_time and object.status == 'paid' %}
              <a href="{% url 'drill_suppers:refund' object.pk %}">
                <button class="btn btn-danger">Cancel Booking</button>
              </a>
            {% endif %}
            <a href="{% url 'drill_suppers:index' %}">
              <button class="btn btn-primary">Book another</button>
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
  {% endtimezone %}
{% endblock content %}

hac_shop/drill_suppers/templates/drill_suppers/transactionrecord_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}


{% block title %}
  Purchase a Drill Supper
{% endblock %}

{% block content %}
  <div class="container-fluid" style="max-width: 500px;">
    <div class="row mt-4">
      <div class="col">
        <h1>Purchase Drill Suppers</h1>
        <p>Book a drill supper at the HAC, which includes a main meal and a dessert.</p>

        <p>Bookings can be made up until 6pm on the day.</p>
      </div>
    </div>
    {% crispy form %}
  </div>
{% endblock content %}

hac_shop/drill_suppers/templates/drill_suppers/transactionrecord_refund.html
{% extends "base.html" %}
{% load tz %}
{% load crispy_forms_tags %}


{% block title %}
  Cancel your drill supper
{% endblock %}

{% block content %}
  {% timezone "Europe/London" %}
  <div class="container-fluid" style="max-width: 500px;">
    <div class="row mt-5">
      <div class="col">
        <div class="card">
          <div class="card-header text-muted text-center">
            {{object.pk}}
          </div>
          <div class="card-body text-center">
            <h1>Cancel your booking</h1>
            <hr />
            <p>
              <span class="fw-bold">{{object.quantity}}x</span> Drill Suppers at the HAC<br />
              from {{object.drill_night.date_time|time:"H:i"}} on {{object.drill_night.date_time|date:"l j F"}}<br />
              for <span class="fw-bold">{{object.name}}</span>
            </p>
            {% if object.status == "paid" %}
              <hr />
              <h2 class="fs-5">Confirm your email to refund</h3>
              {% crispy form %}
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  </div>
  {% endtimezone %}
{% endblock content %}